### ISSUE TITLE
[EPIC] Build System

### ISSUE THREAD

**Issue by thedrow** [getdrifter/drifter-configuration-collector#13]
- [ ] Create a docker container for the configuration collector
- [ ] Set up invoke for managing tasks
- [ ] Create a setup.py file
