### ISSUE TITLE
[EPIC] Handle File Events

### ISSUE THREAD

**Issue by thedrow** [getdrifter/drifter-configuration-collector#40]
- [ ] Handle file addition and removal
- [ ] Handle user and group ownership changes
- [ ] Handle file permission changes
