### ISSUE TITLE
[EPIC] Project Management

### ISSUE THREAD

**Issue by thedrow** [getdrifter/drifter-configuration-collector#6]
- [x] Set up board #5
- [x] Set up label scheme #7 
- [x] Set up board columns #9
